// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvahCpBbrZ3ojN00cD-5Q2O4YyLbnG3jM',
    appId: '1:185092628754:web:857fd39d4c820a62b353cb',
    messagingSenderId: '185092628754',
    projectId: 'ingosstrakh-49b3a',
    authDomain: 'ingosstrakh-49b3a.firebaseapp.com',
    storageBucket: 'ingosstrakh-49b3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRDjciG9zSr2R_-T7wG8NxSR_4emkZpI',
    appId: '1:185092628754:android:b00d6ba63eca113bb353cb',
    messagingSenderId: '185092628754',
    projectId: 'ingosstrakh-49b3a',
    storageBucket: 'ingosstrakh-49b3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmCMHoh9lPwjmuDB0HMjpA20r25aWzAKg',
    appId: '1:185092628754:ios:a45845f30d645976b353cb',
    messagingSenderId: '185092628754',
    projectId: 'ingosstrakh-49b3a',
    storageBucket: 'ingosstrakh-49b3a.appspot.com',
    androidClientId: '185092628754-a5b64ne37ebihup5t33t75anqb950djd.apps.googleusercontent.com',
    iosClientId: '185092628754-7s9ptar3on1h3oduqbdsvggpo31i0i3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ingos',
  );
}
